mpbb: skip install-deps if port has no deps
If a port does not have any dependencies, the port command fails:
$ port install depof:bzip2
Error: No ports matched the given expression

Check for the list of dependencies first and skip this step if it is empty.

git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@146894 d073be05-634f-4543-b044-5fe20cf6d1d6